import com.skptech.drools.demo.model.TaxiRide;
import com.skptech.drools.demo.model.Fare;
import com.skptech.drools.demo.model.DroolsData;
import java.util.*;

global com.skptech.drools.demo.model.Fare rideFare;

dialect "mvel"

rule "Calculate Taxi Fare - Scenario 1"
    when
        DroolsData(fields["isNightSurcharge"] == false && fields["distanceInMile"] < 10)
    then
        rideFare.setNightSurcharge(0L);
        rideFare.setRideFare(70L);
end

rule "Calculate Taxi Fare - Scenario 2"
    when
        DroolsData(fields["isNightSurcharge"] == true && fields["distanceInMile"] < 10)
    then
        rideFare.setNightSurcharge(30L);
        rideFare.setRideFare(70L);
end

rule "Calculate Taxi Fare - Scenario 3"
    when
        taxiRideInstance:DroolsData(fields["isNightSurcharge"] == false && fields["distanceInMile"] >= 10 && fields["distanceInMile"] < 100)
    then
        rideFare.setNightSurcharge(0L);
        rideFare.setRideFare(70+(2 * (long) taxiRideInstance.getFields().get("distanceInMile")));
end

rule "Calculate Taxi Fare - Scenario 4"
    when
        taxiRideInstance:DroolsData(fields["isNightSurcharge"] == true && fields["distanceInMile"] >= 10 && fields["distanceInMile"] < 100)
    then
        rideFare.setNightSurcharge(30 + (long) taxiRideInstance.getFields().get("distanceInMile"));
        rideFare.setRideFare(70+(2 * (long) taxiRideInstance.getFields().get("distanceInMile")));
end

rule "Calculate Taxi Fare - Scenario 5"
    when
        taxiRideInstance:DroolsData(fields["isNightSurcharge"] == false && fields["distanceInMile"] >= 100)
    then
        rideFare.setNightSurcharge(0L);
        rideFare.setRideFare(70+(2 * (long) taxiRideInstance.getFields().get("distanceInMile")));
end

rule "Calculate Taxi Fare - Scenario 6"
    when
        taxiRideInstance:DroolsData(fields["isNightSurcharge"] == true && fields["distanceInMile"] >= 100)
    then
        rideFare.setNightSurcharge(30 + (long) taxiRideInstance.getFields().get("distanceInMile"));
        rideFare.setRideFare(70+(2 * (long) taxiRideInstance.getFields().get("distanceInMile")));
end